### ISSUE TITLE
mario.c 

### ISSUE THREAD

**Issue by jerryb0130** [jerryb0130/mario.c#2]
Im having problems now with the variables I actually had it working once then I changed something and cant get it back but anyway, When I initialize variables it tells me I have already done that in the (inti blah; blah;blah). So I take them out and it tells me i missing undeclared identifier. HeLP

#include <stdio.h>
#include <cs50.h>

int main(void)

int ht;
int i;
int s;
int hash;

{

     //gets prompt from user
        do
    {
        printf("Height:");
        ht = get_int();
      //check to see if int is between 1 and 23 
    }  
        while (ht < 0 || ht > 23);
        
        
        
        
        for (int i = 0; i < ht; i++)
        {
            printf("\n");
        }
        
        for(int s=0; s< ht-i-1; s++)   
            {
                printf(" ");
            }
            
            
        for(int hash = 0; hash<i+2; hash++) 
        {
            printf("#");
        }
        printf("\n");
        
        }
    return 0;
}

**Comment by fabiobenner** [comment]
Your logic is not right to solve this problem.

You need:

1 - create a line for each "height" informed;
2 - for each line you need to create the spaces and hashes

Then it would look something like this:

Height: 4

For (creates line from 1 to 4) {
      Inside this loop creates a whitespace.
      Line 1 will have 4-1 spaces and 1 hash
      Line 2 will have 4-2 spaces and 2 hash
      Line 3 will have 4-3 ...........
}

Here's a start for you to practice:

``` C
#include <stdio.h>
#include <cs50.h>

int main(void)
{
    int ht = 0;
    //gets prompt from user
    do {
        printf("Height:");
        ht = get_int();
        //check to see if int is between 1 and 23 
    } while (ht < 0 || ht > 23);
        
    for (int i = 1; i <= ht; i++)
    {
        printf("line %i\n", i);
        //create col with spaces and hashes here :)
    }
    
    return 0;
}
```

**Comment by fabiorogeriosj** [comment]
Your logic is not right to solve this problem.

You need:

1 - create a line for each "height" informed;
2 - for each line you need to create the spaces and hashes

Then it would look something like this:

Height: 4

For (creates line from i=1 to height=4) {
      Inside this loop creates a col.
}

Here's a start for you to practice:

``` C
#include <stdio.h>
#include <cs50.h>

int main(void)
{
    int ht = 0;
    //gets prompt from user
    do {
        printf("Height:");
        ht = get_int();
        //check to see if int is between 1 and 23 
    } while (ht < 0 || ht > 23);
        
    for (int i = 1; i <= ht; i++)
    {
        printf("line %i\n", i);
        //create col with spaces and hashes here :)
    }
    
    return 0;
}
```
